name: texstudio-arm64

on:
  workflow_dispatch:
    branch: master

jobs:
  build:
    name: 编译构建
    runs-on: ubuntu-24.04-arm
    container: linuxdeepin/deepin:crimson-arm64-v1.6.0

    steps:
    - name: 检查代码
      uses: actions/checkout@v4

    - name: 安装所需依赖
      run: |
        apt update && apt upgrade -y
        apt install -y \
          build-essential cmake git python3-pip make \
          qtbase5-dev libqt5svg5-dev qtdeclarative5-dev qttools5-dev libqt5svg5-dev libpoppler-qt5-dev libpoppler-cpp-dev pkg-config zlib1g-dev libquazip5-dev

    - name: 编译
      continue-on-error: false
      run: |
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=./build/appdir/usr .. -Wno-dev
        cmake --build . --target install -- -j 8

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: texstudio-arm64
        path: ./build
